version: '3.9'

services:
  web:
    image: tutum/apache-php
    hostname: web-php
    ports:
      - '9000:80'
    volumes:
      - ./app-php/db-data:/var/www/html/
    networks:
      - frontend
      - backend

  db:
    image: mariadb
    hostname: mysql
    volumes:
      - ./app-php/db-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
    networks:
      - backend
networks:
  frontend:
  backend:
